services:
  hemrs-frontend:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
  hemrs:
    image: ghcr.io/frixxie/hemrs:latest
    ports:
      - '65534:65534'
    environment:
      DATABASE_URL: postgresql://postgres:admin@db:5432/postgres
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
